### ISSUE TITLE
Save skeleton data

### ISSUE THREAD

**Issue by mahdidrm** [Vangos/kinect-2-coordinate-mapping#1]
I want to save the skeleton features via both kinects. Could you please help me?

**Comment by Vangos** [comment]
The Microsoft Kinect drivers do not support the use of more than 1 Kinect device. You can only have 1 Kinect per computer.

**Comment by mahdidrm** [comment]
I have installed two kinects, (kinect for windows and xbox one) this is not my problem. I am looking for a way to save the skeleton features via Kinect; It is not important which kinect. Could you please help me?

**Comment by Vangos** [comment]
You can check these projects:

* [Kinect to CSV](https://github.com/LightBuzz/Kinect-2-CSV)
* [Kinect video recorder](https://vitruviuskinect.com/)
